import Follow from "./modules/follow-modules/base";
import cleanUp from "./modules/follow-modules/cleanUp";
import validate from "./modules/follow-modules/validate";
import create from "./modules/follow-modules/create";
import deleteFollow from "./modules/follow-modules/deleteFollow";
import isVisitorFollowing from "./modules/follow-modules/isVisitorFollowing";
import getFollowersById from "./modules/follow-modules/getFollowersById";
import getFollowingById from "./modules/follow-modules/getFollowingById";
import countFollowersById from "./modules/follow-modules/countFollowersById";
import countFollowingById from "./modules/follow-modules/countFollowingById";
Follow.prototype.cleanUp = cleanUp;
Follow.prototype.validate = validate;
Follow.prototype.create = create;
Follow.prototype.deleteFollow = deleteFollow;
Follow.prototype.isVisitorFollowing = isVisitorFollowing;
Follow.prototype.getFollowersById = getFollowersById;
Follow.prototype.getFollowingById = getFollowingById;
Follow.prototype.countFollowersById = countFollowersById;
Follow.prototype.countFollowingById = countFollowingById;
export default Follow;
