import User from "./modules/user-modules/_userBase";
import cleanUp from "./modules/user-modules/cleanUp";
import validate from "./modules/user-modules/validate";
import login from "./modules/user-modules/login";
import register from "./modules/user-modules/register";
import getAvatar from "./modules/user-modules/getAvatar";
import findByUserName from "./modules/user-modules/findByUserName";
import doesEmailExist from "./modules/user-modules/doesEmailExist";
User.prototype.cleanUp = cleanUp;
User.prototype.validate = validate;
User.prototype.login = login;
User.prototype.register = register;
User.prototype.getAvatar = getAvatar;
User.prototype.findByUserName = findByUserName;
User.prototype.doesEmailExist = doesEmailExist;
export default User;
