export const addFollowURL = "/addFollow/:username";
export const removeFollowURL = "/removeFollow/:username";
export const createPostURL = "/create-post";
export const viewSinglePostURL = "/post/:id";
export const editPostURL = "/post/:id/edit"; // GET edit screen, POST updates
export const deletePostURL = "/post/:id/delete";
export const searchPostsURL = "/search";
export const userProfilePostsURL = "/profile/:username/posts";
export const userProfileFollowersURL = "/profile/:username/followers";
export const userProfileFollowingURL = "/profile/:username/following";
export const userHomefeedURL = "/homefeed";
export const userRegistrationURL = "/register";
export const userLoginURL = "/login";
export const doesUsernameExistURL = "/does-username-exist";
export const doesEmailExistURL = "/does-email-exist";
export const userLogoutURL = "/logout";
